---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  root_path: /opt/verifier

platforms:
  <% %w[14 13 12].each do |chef| %>
  - name: ubuntu-18.04-chef-<%= chef %>
    driver:
      image: ubuntu:18.04
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
      intermediate_instructions:
        - RUN apt-get update
        - RUN apt-get -y install systemd
  - name: ubuntu-16.04-chef-<%= chef %>
    driver:
      image: ubuntu:16.04
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
  - name: ubuntu-14.04-chef-<%= chef %>
    driver:
      image: ubuntu:14.04
      chef_version: <%= chef %>
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN dpkg-divert --remove /sbin/initctl
        - RUN ln -sf /sbin/initctl.distrib /sbin/initctl
  - name: debian-9-chef-<%= chef %>
    driver:
      image: debian:9
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
      intermediate_instructions:
        - RUN echo DISTRIB_CODENAME=stretch > /etc/lsb-release
        - RUN apt-get update
        - RUN apt-get -y install systemd gnupg
  - name: debian-8-chef-<%= chef %>
    driver:
      image: debian:8
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
      intermediate_instructions:
       - RUN echo DISTRIB_CODENAME=jessie > /etc/lsb-release
  - name: centos-7-chef-<%= chef %>
    driver:
      image: centos:7
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
  - name: centos-6-chef-<%= chef %>
    driver:
      image: centos:6
      chef_version: <%= chef %>
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install upstart initscripts
  - name: fedora-27-chef-<%= chef %>
    driver:
      image: fedora:27
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install procps
  - name: amazon-2-chef-<%= chef %>
    driver:
      image: amazonlinux:2
      chef_version: <%= chef %>
      pid_one_command: /lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install systemd
  - name: amazon-1-chef-<%= chef %>
    driver:
      image: amazonlinux:1
      chef_version: <%= chef %>
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install upstart initscripts
  <% end %>

suites:
  - name: default
    run_list:
      - recipe[snu_python_test::default]
    verifier:
      inspec_tests:
        - test/integration/default
