language: ruby

branches:
  only:
    - master

sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

services:
  - docker

install:
  - chef exec bundle install --without=development

env:
  - SUITE=default PLATFORM=ubuntu
  - SUITE=default PLATFORM=debian
  - SUITE=default PLATFORM=centos
  - SUITE=default PLATFORM=fedora
  - SUITE=default PLATFORM=amazon
  - SUITE=remove PLATFORM=ubuntu
  - SUITE=remove PLATFORM=debian
  - SUITE=remove PLATFORM=centos
  - SUITE=remove PLATFORM=fedora
  - SUITE=remove PLATFORM=amazon

script:
  - chef exec kitchen test $SUITE-$PLATFORM

stages:
  - name: unit
  - name: test
  - name: deploy
    if: NOT type = cron AND branch = master

jobs:
  include:
    - stage: unit
      env:
      script: chef exec rake
    - stage: deploy
      env:
      script: skip
      before_deploy:
        # - TODO: decrypt .travis/configs.tar.gz
        - tar xzf .travis/configs.tar.gz
        - cp .travis/id_rsa ~/.ssh/
        - chmod 0600 ~/.ssh/id_rsa
        - git remote set-url origin git@github.com:socrata-cookbooks/snu_python
      deploy:
        provider: script
        script: chef exec stove --username socrata --key .travis/client.pem
        skip_cleanup: true

notifications:
  slack:
    on_failure: change
    on_success: never
    rooms:
      # TODO: - secure: Connect to Socrata slack
